default: &default
  adapter: postgresql
  pool: 5
  host: <%= ENV['POSTGRES_HOSTNAME'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: bastabiet_development

test:
  <<: *default
  database: bastabiet_test

production:
  <<: *default
  database: bastabiet_production
