# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 836f77ace497442bc1d5621e0de4e14243dab3511f99d6446b8a7082ca342f7e4e059752d8f072fa73fc9fcd9d2614be19aaa2a7c919522910d192d0a9841a89

test:
  secret_key_base: f558933660b6582054fc7454126063dd3ce5e0197144c5a7082289b1550f284dc89a287809e397ee5c777697de0bfa27de111c6c06569d56f8a0de5ca705b118

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
